server: 
  port: 9411
  connection-timeout: 5000
  compression: 
    enabled: true
  servlet: 
    context-path: /
    application-display-name: zipkin_server_9411
  tomcat: 
    basedir: /data/tomcat-tmp/zipkin_server_9411
    uri-encoding: UTF-8
    max-connections: 1000
    max-threads: 500
    min-spare-threads: 20
    accept-count: 100
    accesslog: 
      enabled: true
      directory: logs
      request-attributes-enabled: true

spring:
  application:
    name: hello-zipkin
  sleuth:
    enabled: false
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers:
      - 192.168.1.102:9092
      - 192.168.1.103:9092
      - 192.168.1.104:9092
    
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.102:8761/eureka/
      
  #zipkin的ui界面配置
management:
  metrics:
    web:
      server:
        auto-time-requests: false
        
logging:
  config: classpath:logback-spring-9411.xml